config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  
  resources :definitions do
    collection do
      get :search
    end
  end

  root 'definitions#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
  validates :meaning, presence: true
  validates :part_of_speech, presence: true

  def self.search(search)
    where("word LIKE ? or meaning LIKE ?", "%#{search}%", "%#{search}%")

    # switch development to postgres or attempt to fix below?
    # where("lower(#{resource_class.table_name}.#{key}) LIKE lower(?)", "%#{search}%")

  end

  def fancy?
    word.length > 16
  end

  def self.random
    order("id").offset(rand(count)).first
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_definition, only: [:show, :edit, :update, :destroy]
  before_action :set_random_definition, only: [:index, :search]
  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all
  end

  def search
    @search = params[:search]
    @definitions = Definition.search(@search)
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:word, :meaning, :search, :part_of_speech, :example)
    end

    def set_random_definition
      @random_definition = Definition.random
      Rails.logger.info  "-" * 80 + "    set_random_definition     " + "-" * 80 + @random_definition.inspect

    end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_definition.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p class="word"><%= definition.word %>
      <span class="edit_buttons">
        <%= link_to '', definition, class: "glyphicon glyphicon-info-sign" %>
        <%= link_to '', edit_definition_path(definition),class: "glyphicon glyphicon-pencil" %>
        <%= link_to '', definition, method: :delete, class: "glyphicon glyphicon-trash", data: { confirm: 'Are you sure?' } %>
      </span>
    </p>
    <p class ="part_of_speech"><%= definition.part_of_speech %></p>
    <ol>
      <li><%= definition.meaning %></li>
      <p class="example"><%= definition.example %></p>
    </ol>
  </div>
</div>

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>

  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>
      <ul>
      <% @definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class=" form-group">
      <%= f.label :word %>
      <%= f.text_field :word, size: 50 %>
    </div>
    <div class=" form-group">
      <%= f.label :meaning %>
      <%= f.text_field :meaning, size: 50  %>
    </div>
    <div class=" form-group">
      <%= f.label :part_of_speech %>
      <%= f.select :part_of_speech, ["noun","verb","pronoun","adjective","adverb","preposition","conjunction","interjection"] %>
    </div>
    <div class=" form-group">
      <%= f.label :example %><br>
      <%= f.text_area :example, rows:4, cols: 63 %>
    </div>
    <div>
      <%= f.submit class:"buttons"%>
    </div>
  <% end %>

app/views/definitions/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag 'dic_logo.png', size: "220x90"%>
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
   </div> <!-- Navbar-header -->

    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li><a href="/">Home <span class="sr-only">(current)</span></a></li>
       <li><a href="/definitions/new">New Definition</a></li>

         <li><%= form_tag(search_definitions_path, method: "get", :html => {class:"form-inline navbar-form navbar-right"}) do %>

           <div class="form-group">

             <%= text_field_tag :search, nil, placeholder: "Search Definitions",:html => {class:"form-control"} %>
             <%= submit_tag "Search", class:"buttons"%>

         <% end %></li>

       </div>
       </ul>
   </div> <!-- Navbar-collapse -->


 </div> <!--Container-fluid -->
</nav>

app/views/definitions/edit.html.erb
<div class = "add_form">
  <h1>Editing Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>
</div>

app/views/definitions/index.html.erb
<div class="col-md-7">

  <p id="notice"><%= notice %></p>

  <% if user_signed_in? %>
    <h4>Welcome back, <%= current_user %></h4>
  <% end %>
  <% if @search %>
    <h4>You searched for: <%= @search %></h4>
  <% end %>

  <% if @definitions.empty? %>
    <p class="not_found">Oh no! No results found. =( </p>
  <% else %>
    <h2 class="titles"> Browse Our Dictionary </h2>
  <% end %>

  <div id="search-wait" class="hide"></div>
  <div id="definitions">
    <%= render @definitions %>
  </div>

</div>

<div class="sidebar col-md-5">

  <h2 class="titles"> Word Challenge! </h2>
  <h5 class="titles"> Try to use it today </h5>
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="word"><%= @random_definition.word %></p>
        <p class ="part_of_speech"><%= @random_definition.part_of_speech %></p>
        <ol>
          <li><%= @random_definition.meaning %></li>
          <p class="example"><%= @random_definition.example %></p>
        </ol>
      </div>
    </div>
  <ul>
    <li><a href="/definitions/new" class="buttons standalone">Add New Definition</a></li>
  </ul>

</div>

app/views/definitions/new.html.erb
<div class = "add_form">
  <h1>New Definition</h1>

  <%= render 'form' %>

  <%= link_to 'Back', definitions_path %>
</div>

app/views/definitions/search.js.erb
$("#definitions").html("<%= escape_javascript(render @definitions)%>");

app/views/definitions/show.html.erb
<div class = "add_form">
<p id="notice"><%= notice %></p>
<h1>Definition</h1>
<div class = "show_word">
  <p>
    <strong>Word:</strong>
    <%= @definition.word %>
  </p>

  <p>
    <strong>Meaning:</strong>
    <%= @definition.meaning %>
  </p>

  <p>
    <strong>Part of Speech:</strong>
    <%= @definition.part_of_speech %>
  </p>

  <p>
    <strong>Example:</strong>
    <%= @definition.example %>
  </p>
</div>

<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Idiosyncratic Dictionary</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  </head>
  <body>
    <div class="wrapper">

    <%= render 'shared/navbar' %>
    <%= yield %>

    <footer class="footer">
          <div class="container">
            <p class="text-center">Thank you for visiting!</p>
          </div>
    </footer>
  </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag 'id_logo.jpg', size: "290x45"%>
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
   </div> <!-- Navbar-header -->

    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li><%= link_to "Login", new_user_session_path %></li>
       <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to logout?'}%></li>
       <li><div class="form-inline navbar-form navbar-right"><%= text_field_tag :search, nil, placeholder: "Search Definitions",:html => {class:"form-control"} %></div></li>
     </ul>
   </div> <!-- Navbar-collapse -->

 </div> <!--Container-fluid -->
 <div class="header_img">
   <%= image_tag("words_inspire.jpg", class:"full_img") %>
 </div>
</nav>